// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynvhdjouwqrodzmnshiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inludmhkam91d3Fyb2R6bW5zaGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDM2NzMsImV4cCI6MjA2MDg3OTY3M30.xxpY24pfYXXhYJ5gzqIxAc_-05NZ4Zlrvkd94fJfaaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);